var cards = [
  {"title":"90s kids","description":"90s kids drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Dance or Drink","description":"Do a dance or take a drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Touch the ceiling","description":"Try touch the ceiling without jumping, if you can't then you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"21","description":"Starting with you goiung clockwise from 1, you can either say one, two or three numbers. for example: one, two three, four. The person who says 21 must down their drink","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"Name the Song","description":"If you can name the song playing right now choose someone to drink, if there is no music then you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Take of ya clothes","description":"Choose a player to remove a piece of clothing","type":"normal","rule_rounds":"-1","card_intensity":"25"},
  {"title":"Push left","description":"Push the player on your left","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise natural disasters","description":"Starting with you go round clockwise naming types of natural disaster, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Vegetarians","description":"Vegetarians drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Least phone contacts","description":"The player with the least phone contacts must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Dance Dance Dance","description":"Dance until your next round or down your drink","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Clockwise Beatles Songs","description":"Starting with you go round clockwise naming Beatels Songs, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Drink with me","description":"Pick a payer to drink with you","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Joke","description":"Tell a joke, if no one laughs then you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Past midnight","description":"Drink if it's past midnight","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Baldy","description":"Anyone bald playing? they must drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Single people","description":"All single people must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"10 seconds","description":"Finish your drink in under 10 seconds, if you fail then finish that drink and one more","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Thumb war","description":"Have a thumb war with the player closest","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise Dog Breeds","description":"Starting with you go round clockwise naming Dog Breeds, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Pale ","description":"The most pale player must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Mountain","description":"Do something to the player on your left (for example flick them or push them) they must do that plus one more thing to the player on their left, keep going round clockwise adding steps until someone forgets one, the player who loses must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Bra size","description":"Girls drink for their bra cup size, aa=0, a=1, b=2, c=3 and so on","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Every letter drink","description":"Drink for every letter in your name","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Take a drink from left and right","description":"Take a drink from the player on your right and left","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Isn't straight","description":"Anyone who isn't straight must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Me no english","description":"You must not speak English for one round","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Check your phone","description":"For one round if anyone checks their phone they must drink","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Blue eyed players","description":"Blue eyed players drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Last card memory","description":"Drink if you can't remember your last card","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Fingers pointing","description":"Everyone point at a player, the player with the most fingers pointed at them must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"How many countries","description":"Drink for how many countries you've been to","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Player you've known the longest","description":"The player you have known the longest must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Born in winter","description":"Anyone born in winter drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Swapsies","description":"Swap phones with the player on your right, and then both send one text to anyone you want","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Touch your toes","description":"Touch your toes without bending your legs or take a drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Hum a song","description":"Hum a song, the first player to guess the song can choose someone to drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Females drink","description":"Females drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Favourite book","description":"Tell everyone your favourite book and then drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Tell them","description":"Call someone and tell them you love them","type":"normal","rule_rounds":"-1","card_intensity":"25"},
  {"title":"2 truths 1 lie","description":"Tell everyone two truths and one lie Every player must guess which one is a lie Every player that gets it wrong must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Eyes closed","description":"Play this round with your eyes closed","type":"rule","rule_rounds":"1","card_intensity":"10"},
  {"title":"Seven","description":"Go clockwise counting up from 1, but no player can say a multiple of 7 or a number with 7 in it. Instead they must say 'drink'. When a player says 'drink' the direction changes. First player to mess up must drink.","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Seeing double","description":"Everyone must drink double for one round","type":"rule","rule_rounds":"1","card_intensity":"10"},
  {"title":"British","description":"All british people drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Go find something","description":"The player on your right must find something and bring it to you as a gift","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Next card with the other player","description":"Do the next card with the other player","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Wearing glasses","description":"Everyone wearing glasses must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Forehead kiss","description":"Kiss the closest player to you on the forehead","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"Strange face","description":"Everyone make a strange face and then drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Players with tattoos drink","description":"Players with tattoos drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Mixed drink","description":"If your drink is mixed then take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Heads or Tails","description":"Choose heads or tails and then flip a coin, if correct then everyone except you drinks, if incorrect then you drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Opposite sex swap","description":"Swap a piece of clothing with the closest player of the opposite sex","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Wine drinkers drink","description":"Wine drinkers drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Tripled","description":"Next effect on you is tripled","type":"rule","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Everyone down!","description":"Everyone down their drinks","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Everyone drink","description":"Everyone drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"General knowledge question","description":"Ask the player on your right a general knowledge question, if they are correct then you drink, but if they are wrong they must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Met Today","description":"Any players that met today must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Touch the floor","description":"Everyone must touch the floor, the last to do so must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Silent","description":"Stay silent for one round or drink","type":"rule","rule_rounds":"1","card_intensity":"10"},
  {"title":"Prefer Android","description":"Drink if you prefer android","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Dog owners drink","description":"Dog owners drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Rule 3","description":"You can create a rule that players must follor or drink, for example: 'always be holding your drink' or 'don't look at your phone'","type":"rule","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Can play an instrument","description":"Anyone who can play an instrument drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise US presidents","description":"Starting with you go round clockwise naming US Presidents, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clothes off or drink","description":"Take off a piece of clothing or drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"make out","description":"Pick a player and make out with them","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Take a drink","description":"Take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Everyone but you and me","description":"Choose a player, everyone but you and that player must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Left only","description":"Use only your left hand for one round","type":"rule","rule_rounds":"1","card_intensity":"10"},
  {"title":"Everyone stand up","description":"Everyone stand up, the last person standing must drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Cats or Dogs","description":"Everyone vote if they prefer dogs or cats, the side with the least votes must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Offer me a drink","description":"Everyone must offer you a drink, you can choose one and take a drink from it","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Shortest player","description":"The shortest player must sit on the floor for one round","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Hand on crotch","description":"You must keep one hand on your crotch for a round","type":"rule","rule_rounds":"1","card_intensity":"10"},
  {"title":"Formally dressed","description":"The most formally dressed person must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Largest ears","description":"The player with the largest ears must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Slap bum","description":"Slap the bum of the player on your right","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Skinniest jeans","description":"Whoever is wearing the skinniest jeans must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise Currencies","description":"Starting with you go round clockwise naming different currencies, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Stoners drink","description":"Stoners drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Lie and drink","description":"Lie on your back and drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Swap seats clockwise","description":"Everyone swap seats moving in a clockwise rotation","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Don't drink until your next turn","description":"Don't drink until your next turn","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"look down look up","description":"Everyone look at the ground and on the count of three look up and look at another players eyes. any players making eye ontact with eachother must drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Biggest fear","description":"Tell everyone your biggest fear and then drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Clockwise countries in Asia","description":"Starting with you go round clockwise naming Countries in Asia, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"How many inches?","description":"Men drink for a second for every inch they have","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Boulder","description":"you must drink once, and then the player to your left must drink twice, and then the player to their left three times and so on until it comes back to you","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Same drink","description":"All players with the same drink as you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Compliment me!","description":"Everyone must compliment you or drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Compliment Left","description":"Compliment the person on your left","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Cat owners drink","description":"Cat owners drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Redheads drink","description":"Redheads drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Sill walk","description":"Everyone must do a silly walk and then drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Rhyme","description":"Choose a word and then everyone must go round clockwise saying words that rhyme with that word, the first one to fail must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"One syllable name","description":"Anyone with a one syllable name must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Choose someone to down","description":"Choose someone to down their drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Still as a statue","description":"Stay completely still like a statue for one round","type":"rule","rule_rounds":"1","card_intensity":"5"},
  {"title":"If you can","description":"Drink if you can read this","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Most countries","description":"Whoever has travelled to the most countries must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"You drink double","description":"You have to drink double for one round","type":"rule","rule_rounds":"1","card_intensity":"10"},
  {"title":"Player to your left","description":"The player left of you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Brunettes Drink","description":"Brunettes drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Say cheers","description":"Everyone raise their drinks and say cheers","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Take Three Turns","description":"Take the following three turns","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Waht","description":"If yuo cna raed tihs tehn dinrk","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Piercing","description":"Drink if you have a piercing","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Weakest drink","description":"The player with the weakest drink must take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Green eyed players","description":"Green eyed players drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Most skin","description":"The player showing the most skin must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Opposite Player","description":"The player opposite you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Odd socks","description":"If you are wearing odd socks then drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Turn away and touch shoulder","description":"Turn away from the other players and then one player has to tap your shoulder, if you guess who it was correctly everyone else drinks but if you are wrong you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Drink Twice","description":"Drink twice","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Touch a wall","description":"Everyone must touch a wall, the last person to do so must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Fill and Down","description":"Fill up your cup and then down it","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Shake hands","description":"Shake hands with every player","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Draw on a player","description":"Draw something on a player of your choice","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Only Whisper","description":"You must only whisper until your next turn","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Car brands","description":"Go round clockwise naming car brands, the first person not able to think of a new one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Repeat","description":"Repeat the last card","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Girl shortest hair","description":"The girl with the shortest hair must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Enjoy the taste","description":"If you enjoy the taste of your drink, then take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Drunkest player","description":"The drunkest player must take another drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"DJ Boy","description":"You are the DJ for the next round, if there is music you can control it","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"All players must touch you","description":"All players must touch you, the last to do so must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"If you would...","description":"If you would have sex with another player take a drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Player with the most cash","description":"The player with the most cash on them must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Best Friend","description":"If your best friend is playing then you must both drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Rule 2","description":"You can create a rule that players must follor or drink, for example: 'no players touch the floor' or 'no one say the word what'","type":"rule","rule_rounds":"-1","card_intensity":"10"},
  {"title":"6 months single","description":"Drink if you have been single for 6 months or more","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Last to raise their drink","description":"The last person to raise their drink must take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Truth or dare","description":"Play Truth or Dare","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Single people","description":"Single people drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"One leg","description":"Everyone stand on one leg, the first to fall must drink","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"Drink","description":"Drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Do Nothing","description":"Do nothing","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Pick a side: tea or coffee","description":"Everyone choose which side they prefer, tea or coffee, the smallest side must all drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise Europe Countries","description":"Starting with you go round clockwise naming Countries in Europe, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Spilt Drinks","description":"Any player who has spilt a drink tonight must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Mexican Wave","description":"Take a drink and then the player on your left must take a drink and then the player on their right and then so on until it is back to you","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Blank Card","description":"Do nothing","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"I love you, passionately","description":"Tell the player on your left that you love them, passionately","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Pizza or Burger","description":"Everyone choose which side they prefer, pizza or burgers, the smallest side must all drink","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Staring competition","description":"Have a staring competition with the person in front of you, the loser must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Fill it up","description":"Fill your drink up","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Tilt head","description":"Tilt your head all the way back and take a drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Rock paper Scissors","description":"Play rock paper scissors with the player on your left, loser drinks","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Best smelling","description":"You must smell every player, the best smelling player must drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Blondes Drink","description":"Blondes drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Look alike","description":"Choose which two players look the most alike, they must both drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Hair re-arrange","description":"Re-arrange the hair of the player on your left","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"Animal noise","description":"Every player must make an animal noise and then take a drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"One legged drink","description":"Stand on one leg and drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Brown eyed players","description":"Brown eyed players drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Put ya hands up","description":"Everyone put their hands in the air, the last to do so must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Even Age","description":"If your age is an even number then drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Vodka","description":"Anyone drinking vodka must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"3 adjectives","description":"Pick 3 adjectives to describe the person on your left and then both drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Every sibling","description":"Drink for every sibling you have","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise US States","description":"Starting with you go round clockwise naming US States, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Next go and Next Next go","description":"Take the go of the next player and the player after that","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise movie genres","description":"Starting with you go round clockwise naming movie genres, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Religious","description":"Anyone religious drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Favourite movies","description":"You and the player on your right say your favourite movies, the rest of the players vote which movie is worst, the player with the most votes must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Another player's drink","description":"Pick another player's drink and take a drink from it","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Unemployed","description":"Unemployed Drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Swap right","description":"Swap seats with the player on your right","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Hairiest","description":"hairiest player drinks","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Most kinky","description":"The most kinky player must drink","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Fuck","description":"You cannot swear for 3 rounds. If you swear then you must drink","type":"rule","rule_rounds":"3","card_intensity":"0"},
  {"title":"Insult infront","description":"Insult the player in front of you","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Everyone phone me!","description":"Everyone must try to phone this player, the first to succeed can choose someone to drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Spin a bottle","description":"Spin a bottle and whoever it lands on must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Can't stop until you stop","description":"All players start drinking and can't stop until you stop","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Smartest player","description":"Everyone vote who the smartest player is, they must down their drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Most likely","description":"Starting with you, go round clockwise saying situations like 'who is the most likely to pass out tonight?' count down from three and everyone must point at the player they think is most likely. they must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Would you rather","description":"Play would you rather","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Selfie and drink","description":"Take a selfie with the player on your right and then both drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Pick 3","description":"Pick three players to drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Last Text","description":"Every player must read their last text out loud or drink","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Going to the bar","description":"Starting with you, go round in a circle saying 'im going to the bar and im going to buy...' and add an alcoholic beverage. the next person must name every beverage that has been said so far and add a new one. the first to forget one or repeat one ","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Biggest shoes","description":"The person with the biggest shoe size must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Most buff","description":"Most buff player must drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Bearded","description":"Bearded players drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Not drunk","description":"Anyone who claims they are not drunk must drink","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Youngest player drinks","description":"Youngest player drinks","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Science Question","description":"Ask the player to the left of you a science question, if they are correct you drink, if not they drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Sex with more than 10 people","description":"Anyone who has had sex with more than 10 people must drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Most sober vote","description":"Everyone vote who the most sober player is, they must down their drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Born in summer","description":"Anyone born in summer drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Take player right drink","description":"Take some of the drink from the player on your right and pour it into your drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Longest time no drink","description":"The person who hasn't drunk in the longest time","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Arm Wrestle","description":"Have an arm wrestle with the player on your right, the loser must down their drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Drink Something New","description":"Drink something you haven't drunk today","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Drink if you do sports","description":"Drink if you do sports","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Anyone with a job","description":"Anyone with a job must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Cant play an instrument","description":"Anyone who can't play a musical instrument must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Biggest...","description":"The player with the biggest hands must take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Drink Race","description":"Race the player across from you to finish a drink, the loser must take another drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Kiss Every Player","description":"Kiss Every Player","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Vegans drink","description":"Vegans drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"2 player kiss","description":"Pick two players, they have to kiss eachother or both take a drink","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"Drink","description":"Drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Where and how met","description":"Tell everyone where and how you met the player on your left","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Ignore me","description":"Everyone ignore this player for one round","type":"rule","rule_rounds":"1","card_intensity":"10"},
  {"title":"Virgins","description":"Virgins drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"The band","description":"Go round anti-clockwise starting with you naming bands that start with 'the' the first person who can't think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Hold hands with your left","description":"You must hold hands with the player on your left for one round","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Tallest player","description":"The tallest player must stand up for one round","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Dyed hair","description":"Anyone with dyed hair must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"On their phone","description":"Anyone on their phone right now must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Swap Clothes","description":"Swap a piece of clothing with the player in front of you","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Down your drink","description":"Down your drink","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Finger in drink","description":"Put your finger in the player on your right's drink","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Ever kissed??","description":"If you've ever kissed one of the other players then you must drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Been in a fight","description":"Drink if you've ever been in a fight","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Makeup","description":"Any players wearing makeup must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Americans","description":"All americans drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"left or right","description":"Kiss either the player on your left or right, you choose...","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Riddles","description":"Tell the player on your right a riddle, if you can't think of one or they guess correctly then you must drink, if they can't figure it out they must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Best looking player","description":"Everyone vote who the best looking player is, they must down their drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Banned Word","description":"You can pick a word that is banned for two rounds, if anyone says this word they must drink","type":"rule","rule_rounds":"2","card_intensity":"0"},
  {"title":"Athiests","description":"Athiests drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Longest hair","description":"The player with the longest hair must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Tebahpla","description":"Say the alphabet backwards or drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"The next player who wants to leave","description":"The next player who wants to leave the room must finish their drink","type":"rule","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Last player who drank","description":"The last player who drank must drink again","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Good or bad joke","description":"The player on your right must tell you a joke, you must decide if it's good enough, if it's not they must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Whoever left last","description":"Whoever left the room last must take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise Fruit","description":"Starting with you go round clockwise naming Fruit, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Looking at this card","description":"Everyone looking at this card must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Take off ya clothes","description":"Take off a piece of clothing or drink","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Eaten during this game","description":"Anyone who has eaten during this game must drink","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Picture taken","description":"Everyone who has taken a picture tonight must take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Swap left","description":"Swap seats with the player on your left","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Hug","description":"Hug any player","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"No truths","description":"You can't tell the truth for a whole round, Drink if anyone catches you telling the truth","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Canadians","description":"canadians drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"12345678910","description":"Think of a number from 1-10, the other players must go clockwise guessing the number, whoever gets ir correct can choose someone to drink","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Choose a Theme","description":"Choose a theme. Everyone must go round and name something from that theme until someone can't, the loser must drink. For example: You choose colours and the group must go round naming colours","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Favourite colour match","description":"Everyone say their favourite colour, any players that say the same colour must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Walk in a straight line","description":"Try walk in a straight line, if you fail then you must drink","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Cried this month","description":"Anyone who has cried in the last month must drink in sorrow","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Pass to the left","description":"Everyone pass their drink to their left and let them take a drink","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Chug Card","description":"You may shout 'chug' at any point and everyone has to finish their drinks. can only be used once","type":"rule","rule_rounds":"-1","card_intensity":"0"},
  {"title":"First drunk pirate","description":"If this is your first time playing drunk pirate you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"NOT","description":"All players must end every sentence with 'not' for one round. everyime someone forgets they must drink","type":"rule","rule_rounds":"-1","card_intensity":"0"},
  {"title":"High five","description":"High five the player to your right and then both take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Lick ear","description":"Lick the ear of the player on your right","type":"normal","rule_rounds":"-1","card_intensity":"25"},
  {"title":"Favourite Hobby","description":"Tell everyone your favourite hobby then drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Male longest hair","description":"The male with the longest hair must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Take a drink","description":"Take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Kiss right","description":"Kiss the player on your right or both take a drink","type":"normal","rule_rounds":"-1","card_intensity":"25"},
  {"title":"no nativo","description":"Drink if English isn't your native language","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Look mum no hands!","description":"Take a drink without using your hands","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Do it","description":"Do whatever the player on your left wants, if you can't then drink","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"more Females or males","description":"If there are more females and males then females must drink, if there are more males than females then males must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Best haircut","description":"Everyone vote who has the best haircut, the player with the most votes must take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Left right kiss","description":"The players on your right and left must kiss eachother or drink","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"Truth or lie","description":"Say a statement about yourself, it can be a truth or lie, the other players must colectively decide if it's a truth or a lie. If they are incorrect they must drink, but if they are correct you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Card of Death","description":"Down your drink and then take a shot","type":"normal","rule_rounds":"-1","card_intensity":"30"},
  {"title":"Player to Your Right","description":"Player to your right must drinks","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Quote a movie","description":"Quote a movie, if the player on your left cannot guess the move they must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"You choose - best dressed","description":"You choose which player is best dressed, they must drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Next laugh","description":"The next person to laugh must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Apple owners","description":"Anyone who owns an apple product must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Question Master","description":"For one round if anyone answers a question asked by you they must drink","type":"rule","rule_rounds":"3","card_intensity":"10"},
  {"title":"Beer drinkers","description":"Anyone drinking beer must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Straightest teeth","description":"The player with the straightest teeth must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Drink Three Times","description":"Drink three times","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Guilty pleasure","description":"say your guilty pleasure","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Nex eye contact","description":"The next person to make eye contact with you must drink","type":"rule","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Someone elses drink","description":"If you are drinking someone elses drink, or someone paid for your drink, Thank them and take a drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"You choose - Nicest eyes","description":"You choose which player has the nicest eyes, they must drink","type":"normal","rule_rounds":"-1","card_intensity":"5"},
  {"title":"Drink from every player","description":"Take a drink form every players drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"The floor is lava","description":"Anyone who touches the floor for one round must drink","type":"rule","rule_rounds":"1","card_intensity":"0"},
  {"title":"Smokers drink","description":"Smokers drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Been sick while drinking","description":"Anyone who has been sick while drinking must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Gestures","description":"Make a gesture, the player to the left of you must make that gesture and make another one, keep going round clockwise adding gestures until someone forgets one, the player who forgets one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"You choose -nicest smile","description":"You choose which player has the nicest smile, they must drink","type":"normal","rule_rounds":"-1","card_intensity":"10"},
  {"title":"Lipstick kiss","description":"Anyone wearing lipstick must drink, and kiss someone on the cheek","type":"normal","rule_rounds":"-1","card_intensity":"15"},
  {"title":"Rule 1","description":"You can create a rule that players must follor or drink, for example: 'no one can say any name' or 'players must only use their left hand'","type":"rule","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Biggest nose","description":"The player with the biggest nose must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"DOB","description":"You must say the date of birth of the player ahead of you, if correct they drink, if incorrect you drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Kiss as many players as you want","description":"Kiss as many players as you want, drink for the number of players you don't kiss","type":"normal","rule_rounds":"-1","card_intensity":"20"},
  {"title":"Oldest player drinks","description":"Oldest player drinks","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Anime","description":"Anyone who watches anime must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Different Religion","description":"Everyone with a different religion to you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Never have I ever","description":"Play one round of never have I ever","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Closed eyes guess","description":"Close your eyes and the player on your left must give you a secret drink, if you can guess the drink correctly then they must drink if not then you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise music genres","description":"Starting with you go round clockwise naming music genres, the first to repeat one or not be able to think of one must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Pick a side: red or blue","description":"Everyone choose which side they prefer, Red or Blue, the smallest side must all drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Australians","description":"Australians drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Males drink","description":"Males drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Clockwise names","description":"Go round clockwise pointing at every player and saying their full names, if you can't do it then you must drink","type":"normal","rule_rounds":"-1","card_intensity":"0"},
  {"title":"Beat","description":"Drum a beat on the table, if the player on your right cannot repeat it they must drink","type":"normal","rule_rounds":"-1","card_intensity":"5"}
]
